### ISSUE TITLE
'Import Config' - Not Working Win7

### ISSUE THREAD

**Issue by ghost** [jonthysell/Chordious#85]
Hello,

I don't use Windows, I am only using it for Chordious.

I just did a fresh install of Win7 Home Edition, and only installed Eset AV 10x and .Net 4.5.2.

When I installed 2.0.4 and clicked on Import Config, nothing happened, so I uninstalled and installed 2.0.2, same thing.

So I'm lost, having this fresh install of Win7, which by the way doesn't even have SP1 in it, I have done no Windows updates either, since I'm only using Chordious on the OS, why bother... :)

So this does not work for me to import a config file I saved before on Windows 8 from someone's computer I used before.

Thanks

**Comment by ghost** [comment]
Sorry after making this post, I see I need SP1 installed...

I'll install and see if that helps.

As an end-user, is there any reason to update from 4.5 to 4.5.2?

**Comment by jonthysell** [comment]
Did you do the following?

1. On the source machine, open Chordious, go to Options, Export Config, and check all of the boxes, save the xml file.
2. On the destination machine, open Chordious, go to Options, Import Config, check all of the boxes, and select the xml file from step one.

If that doesn't work, can you attach the xml file to this bug so I can take a look at it?
