### ISSUE TITLE
Horizontal view, color, scales

### ISSUE THREAD

**Issue by Aphexus** [jonthysell/Chordious#98]
Hi, just found your software. Looks like! I have some suggestions.

1. Allow a horizontal view for the scales and chords(I only see vert)

2. Add piano(it's just a single string like scale where the frets are the notes so you might be able to just change the view of the chords and scales visually without having to modify the internals. (it's just a view thing, the internal model doesn't really need to change if it's too complex to do so)

3. Add violin, cello, viola, etc... all the same as chords, just different tuning, # of strings, etc). 

4. Scale is only returning one note per string, should show all the notes across the fretboard with limitations to box patterns.(possibly allow limiting to box with notes outside the box semi-transparent)  [this seems to be a bug but not all notes are being shown]

5. Use colors. It's also important to know the degree's/function of the notes in a scale C major and A minor are not the same scales enough though they have the same notes. Using color which maps scale degree to a color would be useful.

6. Instead of letters allow to show degree's too. R = root, #9, b9, #11, etc. This is more important than knowing the letter names.

7. Allow for a true scale and chord finder by selecting notes on the fretboard and it showing all the scales that fit, sorta like: http://www.all-guitar-chords.com/reverse_scales.php

But even if one adds a single note it should show all the scales that the note belongs too. e.g., adding B-F will give C major, C Harmonic minor, and Gb Major, Gb harmonic minor, etc... and it would be nice if it did it in "real time". Your finding algorithm seems to be slow but it could be done in a thread and it's results updating the list of found items in parallel.

Thanks.

**Comment by jonthysell** [comment]
Thank you for your feedback.

Most of what you're asking can be done manually by editing the diagrams. If it's a default style you want to apply to all of your diagrams, you can change it in the user style editor.

1. You can change the orientation in the diagram/style editor.

<img width="149" alt="chordious C pizygwmk" src="https://user-images.githubusercontent.com/10852185/57167370-63f33400-6db2-11e9-9325-f3232d058ea7.png">

2. Chordious is specifically designed for drawing fretboard diagrams, not tabs or sheet music. I currently have no plans to support anything but fretboard diagrams.
3. Chordious already supports adding custom instruments and tunings.
4. The scale finder works as designed, it shows every combination of a complete scale pattern. However having all the notes in a box is an interesting option, opened #99 to track it.
5. You can change the colors of marks or their text in the diagram/style editor.

<img width="86" alt="chordious C gqyqok1g" src="https://user-images.githubusercontent.com/10852185/57167398-82592f80-6db2-11e9-9689-5462f057d115.png">

Having the finders automatically assign colors is an interesting idea, though I'd really have to think through how best to enable it.

6. You can change the text in the diagram editor. Having the Finders do this automatically is being tracked by #60.

7. Adding a "reverse" finder is being tracked by #91.

**Comment by Aphexus** [comment]
2. No, I simply mean drawing a piano keyboard and displaying the keys as highlighted. Not tab or sheet music. E.g., https://www.pianochord.org/

The main purpose here is to allow visualizing chords for piano. I believe all you really have to do is modify the visual output to display a piano keyboard so very little work has to be done. That is, a piano still is treated as a fretted instrument but just looks different visually.

5. The colors should be by degree or function. E.g., the root will be blue, the 5th red, the #9 purple.
This allows one to quickly see the function of the notes in the chords rather than just black dots, which tells one nothing of how the note behaves in the chord. 


Thanks, I will check out the other stuff.
